info:
  contact: {}
  description: This API manages the notifications of the forecast model
  title: Notification API
  version: "1.0"
paths:
  /healthcheck:
    get:
      consumes:
      - '*/*'
      description: get the status of the server.
      produces:
      - application/json
      responses:
        "200":
          description: Server is up and running
          schema:
            type: string
      summary: Show the status of the server.
      tags:
      - Health
swagger: "2.0"
